before:
  hooks:
    - go mod download
builds:
  -
    goos: [linux, darwin, windows]
    goarch: [386, amd64, arm, arm64]
    main: ./cmd/pertify/main.go
    binary: pertify
archives:
  - wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: graphman
  github:
    owner: moul
    name: homebrew-moul
  commit_author:
    name: moul-bot
    email: "m+bot@42.am"
  homepage: https://manfred.life/
  description: "graph manipulation library and tool"
