[build]
  command = "make _netlify_deps lambda-build"
  functions = "./lambda-build"
  publish = "web"

[build.environment]
  GO_IMPORT_PATH = "moul.io/graphman"

[[redirects]]
  from = "/"
  to = "/pertify"

[[redirects]]
  from = "/api/pertify"
  to = "/.netlify/functions/pertify"
  status = 200
