version: 2.1

orbs:
  moul: moul/build@1.12.1

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/graphman
      - moul/golang-build:
          gopkg: moul.io/graphman
          tag: '1.11'
      - moul/docker-build:
          image: moul/graphman
