version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/moul.io/graphman
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...
