version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/moul.io/graphman
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: make install
      - run: make test
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      - run: PATH=$PATH:$(pwd)/bin make lint
